name: crashlytics_remote_config_fl_22
description: "A new Flutter project for FL22"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^3.4.15
  firebase_analytics: ^10.8.6
  firebase_core: ^2.25.4
  firebase_remote_config: ^4.3.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
