// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGatmDYyXjknQVFynIdgSINpxCyX8u-8',
    appId: '1:330059073478:web:80e9fbd3b6b81f329194c7',
    messagingSenderId: '330059073478',
    projectId: 'crashlytics-281c8',
    authDomain: 'crashlytics-281c8.firebaseapp.com',
    storageBucket: 'crashlytics-281c8.appspot.com',
    measurementId: 'G-926TZ25D3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALoCwNFvxsAngZWyhjPtfZdoJeXqJgB3U',
    appId: '1:330059073478:android:c8b3c6a80db944029194c7',
    messagingSenderId: '330059073478',
    projectId: 'crashlytics-281c8',
    storageBucket: 'crashlytics-281c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjkS0PA7Uuc4LhpM3Qj2JKKpc-_FARgI',
    appId: '1:330059073478:ios:0d33b1da71e7c7e39194c7',
    messagingSenderId: '330059073478',
    projectId: 'crashlytics-281c8',
    storageBucket: 'crashlytics-281c8.appspot.com',
    iosBundleId: 'com.pdp.crashlyticsRemoteConfigFl22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyjkS0PA7Uuc4LhpM3Qj2JKKpc-_FARgI',
    appId: '1:330059073478:ios:6a4109530cb3f2ad9194c7',
    messagingSenderId: '330059073478',
    projectId: 'crashlytics-281c8',
    storageBucket: 'crashlytics-281c8.appspot.com',
    iosBundleId: 'com.pdp.crashlyticsRemoteConfigFl22.RunnerTests',
  );
}
